services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fintech-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fintech_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      ENCRYPTION_KEY: "your-256-bit-encryption-key-here"
      JWT_SECRET: "c2VjcmV0LWtleS1mb3ItZGV2ZWxvcG1lbnQtYW5kLXRlc3Rpbmctb25seQ=="
      ALPHAVANTAGE_API_KEY: "demo"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - fintech-network

  postgres:
    image: postgres:14-alpine
    container_name: fintech-db
    environment:
      POSTGRES_DB: fintech_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fintech-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: fintech-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fintech.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - fintech-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - fintech-network

volumes:
  postgres_data:

networks:
  fintech-network:
    driver: bridge
