spring:
  security:
    filter:
      order: 10
  datasource:
    url: jdbc:postgresql://localhost:5432/fintech
    username: postgres
    password: postgres

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true
